import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEthers } from "@usedapp/core";
import TokenList from 'components/TokenList';
import { useState } from 'react';

export default function Home({ data: { tokens } }) {

  const { activateBrowserWallet, deactivate, account } = useEthers()
  const [connected, setConnected] = useState(false)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button onClick={() => { account ? deactivate() && setConnected(false) : activateBrowserWallet() && setConnected(true) }}>
            {account ? account.toString() : 'Connect Wallet'}
          </button>

          {account ? <TokenList data={tokens} account={account.toString()} /> : null}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export async function getStaticProps() {
  // Fetch data from external API
  const res_tokens = await fetch(`https://tokens.coingecko.com/uniswap/all.json`)
  const data = await res_tokens.json()

  // Pass data to the page via props
  return { props: { data } }
}